language: python

python:
    - "2.6"
    - "2.7"

branches:
    only:
        - master

install:
    - pip install nose
    - pip install Jinja2==2.6
    - pip install Django==1.4.4

script:
    - make travis